Add python3.9 support
bswck/commonvars pull request #2
Opened 2023-07-21 14:26 UTC by heckad

https://github.com/bswck/commonvars/issues/1

2023-07-21 15:38 UTC, bswck requested changes
Thanks a lot for contributing! Please have a look at the comment below and I'll merge your PR as quickly as possible. 🚀

2023-07-21 15:38 UTC, bswck commented on commonvars/__init__.py
> +    cls: "type[_T] | None",
I'd be very happy to merge this PR unless it had manual string annotations like here.
Can we just make it `from __future__ import annotations` on top and not touch particular annotations?

2023-07-21 18:19 UTC, bswck approved these changes
Perfect. 💯

2023-07-21 18:19 UTC, merged

2023-07-22 16:04 UTC, heckad commented
New release?

2023-07-24 05:46 UTC, bswck commented
> New release?

Ready!